development:
  adapter: postgresql
  encoding: unicode
  database: lyrics_development
  pool: 5
  username: eli
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lyrics_test
  pool: 5
  username: eli
  password:

production:
 adapter: postgresql
 encoding: unicode
 database: lyrics_production
 pool: 5
 username: eli
 password:
